---
- block:
  - name: get app creation role
    git:
      repo: "https://gbmeuk@bitbucket.org/mesoform/create-concierge-app.git"
      dest: "{{ playbook_dir }}/create-concierge-app/"
  - name: get image creation role
    git:
      repo: "https://gbmeuk@bitbucket.org/mesoform/create-concierge-image.git"
      dest: "{{ playbook_dir }}/create-concierge-image/"
#  - name: get application tests role
#    git:
#      repo: "https://gbmeuk@bitbucket.org/mesoform/create-concierge-tests.git"
#      dest: "{{ playbook_dir }}/create-concierge-tests/"

  tags:
    - system_tests
    - all_tests
    - integration_tests
    - build
    - configure